Add shadcn/ui library and base components
naugtur/meetjs.pl pull request #1
Opened 2024-07-03 20:32 UTC by conrisc

2024-07-03 20:47 UTC, ssynowiec requested changes
2 rzeczy do poprawki

2024-07-03 20:47 UTC, ssynowiec commented on package.json
> +	"packageManager": "pnpm@9.4.0+sha1.9217c800d4ab947a7aee520242a7b70d64fc7638"
masz nieprawidłową wersję, tego tu nie powinno być

2024-07-03 20:47 UTC, ssynowiec commented on package.json
> +		"@radix-ui/react-slot": "^1.1.0",
prawdopodobnie w tych wersjach występuje jeszcze błąd z react 19 wersje RC mają już go naprawiony

2024-07-03 21:11 UTC, conrisc commented on package.json
> +		"@radix-ui/react-slot": "^1.1.0",
nie widze nigdzie wercji RC dla tych komponentow, a wydaje sie, ze ta wersja jest jak najbardziej ok dla react 19rc

<img width="532" alt="image" src="https://github.com/ssynowiec/meetjs.pl/assets/19625947/1d2535ae-9128-40ff-afa9-c9469c6d4310">

2024-07-04 07:57 UTC, ssynowiec commented
![Arc 2024-07-04 09 55 00](https://github.com/ssynowiec/meetjs.pl/assets/52856724/ce24bc9e-f6b7-4550-aa48-2b0250c2c0b8)

2024-07-04 12:00 UTC, ssynowiec approved these changes

2024-07-04 12:04 UTC, merged