Warsaw
naugtur/meetjs.pl pull request #32
Opened 2024-08-09 14:26 UTC by dzienisz

<img width="420" alt="Screenshot 2024-08-09 at 16 24 45" src="https://github.com/user-attachments/assets/61f48a2e-4684-48dc-b72e-655332d30faa">

2024-08-09 19:00 UTC, ssynowiec requested changes
bad background source in wrocław page after change image folder

2024-08-09 19:00 UTC, ssynowiec commented on src/app/(cities)/wroclaw/page.mdx
> +<CityBanner city="Wrocław" background="wroclaw.jpeg" />
bad background source

2024-08-12 11:33 UTC, dzienisz commented on src/app/(cities)/wroclaw/page.mdx
> +<CityBanner city="Wrocław" background="wroclaw.jpeg" />
fixed

2024-08-14 14:51 UTC, ssynowiec approved these changes

2024-08-14 15:06 UTC, merged