feat: add info about looking for organizers to cities
naugtur/meetjs.pl pull request #65
Opened 2024-11-13 21:21 UTC by dzienisz

2024-11-13 21:25 UTC, ssynowiec requested changes
1.
<img width="677" alt="image" src="https://github.com/user-attachments/assets/03145fcb-23ef-4488-b295-48b43f2514ff">
2. Niektóre miasta które zrobiłeś, mają swoich organizatorów tylko nie są page stworzone

2024-11-13 23:35 UTC, dzienisz commented
wiem, ale dopóki nie są wypełnione chciałem trochę upiększyć

2024-11-15 15:56 UTC, ssynowiec commented
> wiem, ale dopóki nie są wypełnione chciałem trochę upiększyć

pomyślę nad tym. Można by coś w stylu "stwórz stronę tego miasta poprzez PR", "organizujesz meetup w tym mieście? - uzupełnij tą stronę"

2024-11-15 16:09 UTC, dzienisz commented
Możemy to na ten moment zaakceptować? To, co jest teraz, bardzo źle wygląda.

2024-11-18 13:57 UTC, ssynowiec approved these changes

2024-11-18 14:20 UTC, merged